name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: 
  push:
    branches:
      - main

jobs: 
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents:  write

    steps:
      - name: Generate Snake Animation
        uses:  Platane/snk@v3
        with: 
          github_user_name: rayfansatria
          outputs: |
            dist/github-contribution-grid-snake-dark.svg? palette=github-dark

      - name: Push to output branch
        uses:  crazy-max/ghaction-github-pages@v4
        with: 
          target_branch: output
          build_dir:  dist
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
