name: Update README with Recent Activity

on:
  schedule:
    - cron:  "*/30 * * * *"  # Setiap 30 menit
  workflow_dispatch:        # Manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update README with recent activity

    steps:
      - uses: actions/checkout@v4

      - uses: jamesgeorge007/github-activity-readme@master
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
